import {
  Button,
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  Textarea,
} from '@dge/ui-core';

type ReviewAiContentDialogProps = {
  open: boolean;
  setOpen: (open: boolean) => void;
  editedContent: string;
  setEditedContent: (editedContent: string) => void;
  handleAccept: () => void;
  handleDiscard: () => void;
};
export function ReviewAiContentDialog({
  open,
  setOpen,
  editedContent,
  setEditedContent,
  handleAccept,
  handleDiscard,
}: ReviewAiContentDialogProps) {
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="sm:max-w-[600px]">
        <DialogHeader>
          <DialogTitle>Review AI-Generated Content</DialogTitle>
        </DialogHeader>
        <DialogDescription>
          Please review the content generated by the AI and make any necessary
          edits.
        </DialogDescription>
        <Textarea
          value={editedContent}
          onChange={(e) => setEditedContent(e.target.value)}
          className="min-h-[200px]"
        />
        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={handleDiscard}>
            Discard
          </Button>
          <Button onClick={handleAccept}>Accept</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
